### ISSUE TITLE
About the dataset

### ISSUE THREAD

**Issue by FCYtheFreeman** [oseiskar/pac2018_team_utastoot#1]
Hey,
Congrats that your team took the 2nd palce in PAC 2018 competiton. I really want to take part in it but sadly I knew this competiton just few days ago. I still want to try it now but I can not get the data download link on the official website now. So I wonder if it's possible for you to give me the download link or where I can find those data?
Thanks a lot.

**Comment by oseiskar** [comment]
Hi. Unfortunately, this is not possible as redistribution of the dataset was explicitly forbidden in the terms we agreed to on downloading it. You have to ask the [comptetition organizers](https://www.photon-ai.com/index#contact) if they can grant you access to the dataset.
